PREFIX : <http://www.oxfordsemantic.tech/f1demo/>

# A CONSTRUCT diagram to show data model
CONSTRUCT {?S ?P ?O}
WHERE {
  SELECT DISTINCT ?S ?P ?O
  WHERE {
    ?se ?P ?oe .
    ?se a ?S .
    {?oe a ?O}
    UNION
    { ?se ?P ?oe 
      FILTER(ISLITERAL(?oe))
      BIND(DATATYPE(?oe) AS ?O)}
    }

}