PREFIX : <http://www.oxfordsemantic.tech/f1demo/>

# Most races run without ever getting a podium
SELECT ?forename ?surname ?raceCount
WHERE {
#Much cleaner, isn't it?
    ?driver a :DriverWithoutPodiums ;
        :drivers_forename ?forename ;
        :drivers_surname ?surname ;
        :hasRaceCount ?raceCount .
}
ORDER BY DESC(?raceCount)