PREFIX : <http://www.oxfordsemantic.tech/f1demo/>

# Now we look at the last query, but this time using rules.
# It will be faster, and much easier to read and write.

SELECT ?driverName ?raceCount ?percentageFinal
WHERE {

?driver a :drivers ;
        :drivers_forename ?forename ;
        :drivers_surname ?surname ;
        :hasRaceCount ?raceCount .

OPTIONAL { ?driver :hasWinPercentage ?percentage }       
BIND(CONCAT(?forename, " ", ?surname) AS ?driverName)
BIND(COALESCE(?percentage,0) AS ?percentageFinal)
FILTER(?raceCount > 5)

}
ORDER BY DESC(?percentageFinal)